== INTRODUCTION

This second edition of Practical Gremlin is an evolving guide to the Apache TinkerPop
Gremlin graph query and traversal language, built around real examples using 
real-world graph data. It is written for developers and practitioners who want to 
learn Gremlin by doing, with a focus on practical patterns, working traversals, and 
lessons learned from applying graph technology to real problems.

CAUTION: Feedback on this book is very much encouraged and welcomed! Please open
 https://github.com/krlawrence/graph/issues[GitHub issues] as appropriate.

=== Welcome to the second edition

Practical Gremlin was first published in 2017. In the years that followed, the Apache
TinkerPop graph computing framework has continued to evolve. While it was possible
to keep the first edition mostly up to date and to publish periodic updates, there
comes a time when so much has changed that it makes more sense to take a step back
and release a second edition. The book has been updated to include the most recent
new features added to the Gremlin query language and related technologies. Material
such as discussions of migrating from old versions of Gremlin, and discussions of how
to work around features then lacking, but since added, have been removed. The
following paragraph was used to introduce the first edition. It remains as true today
as it was then. 

[quote, Practical Gremlin first edition, October 2017]
____
The title of this book could equally well be '"A getting started
guide for users of graph databases and the Gremlin query language featuring hints,
tips, and sample queries"'. It turns out that is a bit too long to fit on one line for
a heading but in a single sentence that describes the focus of this work pretty well.
____

As with the first edition, I have resisted the urge to cover every single feature of
TinkerPop one after the other in a reference manual fashion. Instead, what I have
tried to do is capture the learning process that I myself have gone through using
what I hope is a sensible flow from getting started to more advanced topics. To get
the most from this book, I recommend having the Gremlin Console open, with the air
route sample data loaded, as you follow along. I have not assumed that anyone reading
this book has any prior knowledge of Apache TinkerPop, the Gremlin query language, or
related tools.  Everything you need to get started is introduced in Chapter 2.

I hope people continue to find what follows useful. It definitely remains a work in
progress as the Apache TinkerPop framework, and in particular, the Gremlin query
language, continues to evolve.

The book is available in multiple formats including PDF, HTML, ePub, and MOBI. Those
versions, along with sample code and data, can be found at the
https://github.com/krlawrence/graph[project's home on GitHub]. You will find a
summary of everything that is available in the "<<samplesintro>>" section.

=== How this book came to be

I forget exactly when, but sometime early in 2016 I started compiling a list of
notes, hints, and tips, initially for my own benefit. My notes were full of things I
had found poorly explained elsewhere while using graph databases and especially while
using Apache TinkerPop, Gremlin, and JanusGraph. Over time that document continued to
grow and had effectively become a book in all but name. After some encouragement from
 colleagues, I decided to release my notes as a 'living book' in an open source venue
so that anyone who is interested can read it. It is definitely aimed at programmers
and data scientists, but I hope it is also consumable by anyone using the Gremlin
graph query and traversal language to work with graph databases.

I have included a large number of code examples and sample queries along with
discussions of best practices and more than a few lessons I learned the hard way,
that I hope you will find informative. I call it a 'living book' as my goal is to
regularly make updates as I discover things that need adding while also trying to
keep the content as up to date as possible as Apache TinkerPop itself evolves.

I remain extremely grateful to all those who have encouraged me to keep going with
this adventure. Keeping up with a moving target requires a fair bit of work, but it
remains a lot of fun!

Kelvin R. Lawrence +
First draft (first edition): October 5th, 2017 +
Final draft (first edition): May 4th, 2022 +
First draft (second edition): January 1, 2026
Current draft (second edition): {draftdate} +

=== Providing feedback

Please let me know about any mistakes you find in this material, and also, please
feel free to provide feedback of any sort. Suggested improvements are especially
welcome. A good way to provide feedback is by opening an issue in the GitHub
repository located at https://github.com/krlawrence/graph. You are currently reading
revision {revision} of the book.

NOTE: The change history contains details of everything that has been added over time
and can be found at this location:
https://github.com/krlawrence/graph/blob/main/ChangeHistory.md

I am grateful to those who have already taken the time to review the manuscript and
open issues or submit pull requests.

[[thanks]]
=== Some words of thanks

No open source project can succeed without dedicated contributors and equally
dedicated users. Apache TinkerPop continues to be not just a technology, but a
vibrant community as well. This book would have no audience but for the continued
hard work, and interest, of that community.

As always, special thanks should go to, Marko Rodriguez, Daniel Kuppitz, Stephen
Mallette, and others, who created TinkerPop and Gremlin, and drove its evolution for
many years. I'm also grateful to Stephen for his help in putting this second edition
of the book together.

Inspiration as to what topics people are interested in often comes from seeing the
active discussions on-line at venues such as
https://stackoverflow.com/questions/tagged/gremlin[StackOverflow] and the
https://groups.google.com/forum/#!forum/gremlin-users[Gremlin Users Google Group].
Since the first edition of this book was released, Apache TinkerPop now also has an
active https://discord.gg/tinkerpop[Discord server] where many exciting topics get 
discussed daily.

I continue to be grateful for the contributions of my former colleagues, Graham
Wallis, Jason Plurad, and Adam Holley, who helped refine and improve several of the
example queries contained in the first edition of this book. Gremlin is definitely a
bit of a team sport. We spent many fun hours discussing the best way to handle
different types of queries and traversals!

Lastly, I would like to thank everyone who has submitted feedback and ideas via
e-mail or GitHub issues, and pull requests. That is the best part about this
being a 'living book' we can continue to improve and evolve it just as the technology
it is about continues to evolve. Your help and support is very much appreciated.

=== Thoughts on the Second Edition

Except for this section, references to "I" in this book refer to the book's original
author, Kelvin Lawrence. As the editor and co-author of the Second Edition, I didn't
feel as though "I" should become "We" anywhere, as I believe that much of the appeal
of this book lies in Kelvin relating his personal discoveries on his journey with 
Gremlin. I've tried to preserve that feeling and voice as much as possible in my 
many additions and edits.  

As I write this section, I realize that I've authored many lines of TinkerPop's 
Reference Documentation, Tutorials, and Recipes over the years and, as a result, I 
tend to think there is a certain completeness to the documentation that is officially
offered. I think that's a valuable aspect of the TinkerPop project, yet I've also 
always recognized the importance and impact of this book as a resource for Gremlin 
users. My personal opinion is that its approach and organization is what allows it to
make that helpful impact. Where TinkerPop Documentation has its completeness 
presented all at once, this book gives you a clear, ramped process to learning 
Gremlin so that you can make use of that completeness in the official documentation.

In 2023, TinkerPop was in the midst of releasing 3.6.x and 3.7.x release lines which
had introduced a number of important new features. Kelvin and I started realizing 
that Practical Gremlin was falling behind TinkerPop's continued evolution
significantly. With even bigger sets of changes expected on the horizon with 4.0, it
felt as though it was time to make an organized effort to produce an updated
Second Edition.

We officially announced that work had started on it in September 2023 and with the 
big release of 3.8.0 in November 2025, we believed it time to polish up the draft and
make an official publication of the new edition. As with the First Edition, we expect
the book to continue to be a work-in-progress and will make minor publications as new
TinkerPop releases appear.

As you read this edition, please keep in mind that it reflects the state of Gremlin
and TinkerPop at a particular point in time, but it is also part of an ongoing 
conversation with the community. Your questions, suggestions, and examples help shape
where the book goes next. If you find places where it could be clearer, more helpful,
or more complete, your feedback is welcome and will help guide future updates.

Stephen Mallette +
Second edition editor and co-author +

[[about]]
=== What is this book about?

This book is about learning to think in Gremlin by working through practical
examples. It focuses on how to express real graph questions as traversals, how to 
read and reason about Gremlin code, and how to apply common patterns to your own 
graphs. As the book evolves, new examples and refinements continue to be added, but 
the core goal remains the same: to help you build an intuitive understanding of how 
Gremlin works.

In this book you will find real examples featuring real-world graph data. That data,
along with sample code and example applications, is available for download from the
GitHub project as well as many other items. The graph, 'air-routes', is a model of
the world airline route network between 3,504 airports, including 50,637 routes. The
examples presented will work unmodified with the `air-routes.graphml` file loaded 
into the Gremlin console running with a TinkerGraph. How to set that environment up 
is covered in the "<<gremlininstall>>" section below.

NOTE: The examples in this book have been tested using Apache TinkerPop release
{tpvercheck}.

TinkerGraph is an 'in-memory' graph, meaning nothing gets saved to disk
automatically. It is included as part of the Apache TinkerPop download. The goal of
this tutorial is to allow someone with little to no prior knowledge to get up and
going quickly using the Gremlin Console and the 'air-routes' graph. Later in the book
we discuss writing standalone applications in other programming languages such as 
Java, Groovy, and Python.

NOTE: The first few sections of the book focus on showing some basic Gremlin queries
that are both useful and yet easy to understand. By the end of Chapter 3 you should
have a basic understanding of how to explore the air-routes graph using commonly used
Gremlin steps. Chapters 4, 5, and 6 explore Gremlin in more depth.

.How this book is organized
Chapter 1 – INTRODUCTION::
- We start our journey with a brief introduction to Apache Tinkerpop and a quick look
  at why Graph databases are of interest to us. We also discuss how the book is
  organized and where to find additional materials, such as sample code and data
  sets. 
Chapter 2 – GETTING STARTED::
- Many of the examples throughout the book use the Gremlin Console and TinkerGraph,
  and both are introduced in this chapter. We also introduce the air-routes example
  graph - `air-routes.graphml` -  used throughout the book.
Chapter 3 – WRITING GREMLIN QUERIES::
- Now that the basics have been covered, things start to get a lot more interesting!
  It's time to start writing Gremlin queries. We
  briefly explore how we could have built the 'air-routes' graph using a
  relational database, and then look at how SQL and Gremlin are both similar in some
  way,s and very different in others. We then introduce several of the key Gremlin
  query language '"steps"'. We focus on exploring the graph rather than changing it
  in this chapter.
Chapter 4 – BEYOND BASIC QUERIES::
- Having now introduced Gremlin in some detail, we introduce the Gremlin steps that
  can be used to create, modify, and delete, data. We present a selection of best
  practices and start to explore some more advanced query writing.
Chapter 5 – MISCELLANEOUS QUERIES AND THE RESULTS THEY GENERATE::
- Using the Gremlin steps introduced in Chapters 3 and 4, we are now ready to use
  what we have learned so far and write queries that analyze the air-routes graph in
  more depth and answer more complicated questions. The material presented includes
  a discussion of analyzing distances, route distribution, and writing geospatial
  queries.
Chapter 6 – MOVING BEYOND THE GREMLIN CONSOLE::
- The next step in our journey is to move beyond the Gremlin Console and take a look
  at interacting with a TinkerGraph using Java and Groovy applications.
Chapter 7 – INTRODUCING GREMLIN SERVER::
- Our journey so far has focused on working with graphs in a "directly attached"
  fashion. We now introduce Gremlin Server as a way to deploy and interact with
  remotely hosted graphs.
Chapter 8 – COMMON GRAPH SERIALIZATION FORMATS::
- Having introduced Gremlin Server, we take a look at some common Graph serialization
  file formats along with coverage of how to use them in the context of TinkerPop
  enabled graphs. We take a close look at the TinkerPop GraphSON (JSON) format, which
  is used extensively when using Gremlin queries in conjunction with a Gremlin
  Server.
Chapter 9 – FURTHER READING::
- Our journey to explore Apache TinkerPop and Gremlin concludes with a look at
  useful sources of further reading. We present links to useful websites where you
  can find tools and documentation for many of the topics and technologies covered in
  this book.

[[samplesintro]]
=== Introducing the book sources, sample programs, and data

All work related to this project is being done in the open at GitHub. A list of where
to find the key components is provided below. The examples in this book make use of a
sample graph called 'air-routes' which contains a graph based on the world airline
route network between over 3,504 airports. The sample graph data, quite a bit of
sample code, and some larger demo applications can all be found at the same GitHub
location that hosts the book manuscript. You will also find releases of the book
in various formats (HTML, PDF, DocBook/XML, MOBI, and EPUB) at the same GitHub
location. 

The sample programs include standalone Java, Groovy, Python, and Ruby examples as well
as many examples that can be run from the Gremlin Console. There are some differences
between using Gremlin from a standalone program and from the Gremlin Console. The 
sample programs demonstrate several of these differences. The sample applications 
area contains a full example HTML and JavaScript application that lets you explore 
the 'air-routes' graph visually. The home page for the GitHub project includes a 
README.md file to help you navigate the site. Below are some links to various 
resources included in this book.

.Where to find the book, samples, and data
Project home::
- https://github.com/krlawrence/graph
Book manuscript in Asciidoc format::
- This file can be viewed using the GitHub web interface. It will always represent
the very latest updates.
- https://github.com/krlawrence/graph/tree/main/book
Latest PDF and HTML snapshots::
- These files are regularly updated to reflect any significant changes. These are the
only generated formats that are updated outside the full release cycle. The PDF
version includes pagination as well as page numbering and is produced using an A4
page size. The HTML version does not include these features. Otherwise, they are
more or less identical.
- https://kelvinlawrence.net/book/PracticalGremlin.pdf
- https://kelvinlawrence.net/book/PracticalGremlin.html
Official book releases in multiple formats::
- Official releases include AsciiDoc, HTML, PDF, ePub, MOBI, and DocBook versions as
well as snapshots of all the samples and other materials in a single package 
available through GitHub Releases. The eBook and MOBI versions are really intended to
be read using e-reader devices, and for that reason use a white background for all
source code highlighting to make it easier to read on monochrome devices.
- I recommend using the PDF version if possible as it has page numbering. If
you prefer reading the book as if it were a web page, then by all means use the HTML
version. You will just not get any pagination or page numbers. The DocBook format
can be read using tools such as Yelp on Linux systems, but is primarily included
so that people can use it to generate other formats that I do not already provide.
The MOBI and ePub versions may require you to change the font size you use on your 
device to make things easier to read.

- https://github.com/krlawrence/graph/releases
Sample data (`air-routes.graphml`)::
- https://github.com/krlawrence/graph/tree/main/sample-data
Sample code::
- https://github.com/krlawrence/graph/tree/main/sample-code
Example applications::
- https://github.com/krlawrence/graph/tree/main/demos
Change history::
- If you want to keep up with the changes being made, this is the file to keep an eye
on.
- https://github.com/krlawrence/graph/blob/main/ChangeHistory.md

[[tpevolution]]
=== Apache TinkerPop Evolution

Over the last 15 years, TinkerPop, and especially Gremlin, have evolved substantially
from their earliest versions. What we now know as Apache TinkerPop is the result of
an open source project created in 2009 and moved to the Apache Software Foundation
(ASF) in 2015, after the final release of TinkerPop version 2.  The first official
release of Apache TinkerPop 3.0 came in July 2015, with the project being promoted
to Apache's "top-level" status the following year. After a decade of continuous 
releases for TinkerPop 3.0, the project released a beta version of 4.0 in January
2025 for early evaluation.

We focus this second edition of the book on the semantics of Gremlin as of TinkerPop
release 3.8.0.

If you are new to TinkerPop and Gremlin, you can probably skip the next few sections.
They appeared in a slightly modified form, as part of the First Edition, and provided
a way to highlight the arrival of key new features. These notes have been left in the
Second Edition as there are still people using older versions of Gremlin, and it can
be useful to have a list like this to cross-reference.

NOTE: The complete ApacheTinkerPop change history can be found at
https://github.com/apache/tinkerpop/blob/master/CHANGELOG.asciidoc

Graph database engines that support Apache TinkerPop often take a while to move up to
new releases, and it's always a good idea to verify the exact level the database you
are using supports.

This version of the book covers features of Gremlin available as part of the
TinkerPop {tpvercheck} release. As appropriate, notes and examples have been added
that show other ways to perform tasks that new features may simplify. In some cases,
notes have been added to point out when more recent features first appeared.

[[tp34intro]]
==== TinkerPop 3.4

A major update to Apache TinkerPop, version 3.4.0, was released in January 2019, and
a number of point releases followed.

NOTE: Full details of all the new features added in the TinkerPop 3.4.x releases can 
be found at the following link:
https://github.com/apache/tinkerpop/blob/3.4-dev/CHANGELOG.asciidoc

[[tp35intro]]
==== TinkerPop 3.5

Apache TinkerPop 3.5.0 was released in May 2021. This update introduced a number of
improvements in areas such as Gremlin client drivers, the Gremlin Server, and overall
bug fixes. The release also improved the Gremlin query language in some key areas.
Some features that had been declared deprecated in earlier releases were finally
removed as part of the 3.5.0 update. If you have queries and code that still use
these deprecated features, as part of an upgrade to the 3.5.x level, you will need to
make the appropriate changes.

The main breaking change to be aware of is that 'Order.incr' and 'Order.decr' were
removed from the Gremlin language. The newer 'Order.asc' and 'Order.desc' must be
used instead. The examples in this book and those in the `sample-code` folder have
been updated to reflect these changes.

In January 2022, the TinkerPop 3.5.2 release added a native `datetime` operator to
the Gremlin language such that dates can be added without needing programming
language specific constructs. This is useful when sending Gremlin queries as text
strings.

NOTE: Full details of all the new features added in the TinkerPop 3.5.x releases can
be found at the following link:
https://github.com/apache/tinkerpop/blob/3.5-dev/CHANGELOG.asciidoc

[[tp36intro]]
==== TinkerPop 3.6

Apache TinkerPop 3.6.0 was released in April 2022. Coming almost exactly a year after
the initial 3.5.0 release, this is one of the most significant TinkerPop releases
since TinkerPop 3.4.0 appeared in January 2019. The release contains many
improvements, including several new Gremlin steps, designed to make commonly
performed tasks much easier. Notable improvements include:

- New 'mergeV' and 'mergeE' steps that make "create if not exist"
type queries, sometimes referred to as "upserts", much easier to write. Over time,
these steps will replace the use of the 'fold...coalesce' pattern and will also
replace the various "map injection" patterns that can be used to create multiple
vertices and edges in a single query.
- A new 'TextP.regex' predicate that allows regular expressions to be
used when comparing strings.
- The 'property' step can now be given a map of key/value pairs so that several
properties can be created at once.
- A new 'element' step that can be used to find the parent element (vertex or edge)
of a property.
- A new 'call' step that lays the foundation enabling Gremlin queries to call other
endpoints. This opens up many types of interesting use cases such as query
federation, and looking up values from other services.
- A lot of effort has been put into removing unnecessary exceptions by filtering out
parts of traversals instead of failing with an error. This is especially so in the
case of 'by' modulators that now filter when a value does not exist rather than
throw an exception. This work began as part of the TinkerPop 3.5.2 update and is
completed as of TinkerPop 3.6.0.
- A new 'fail' step that can be used to abort a query in a controlled way.

NOTE: Full details of all the new features added in the TinkerPop 3.6.x releases can 
be found at the following link:
https://github.com/apache/tinkerpop/blob/3.6-dev/CHANGELOG.asciidoc

[[tp37intro]]
==== TinkerPop 3.7

TinkerPop 3.7.0 was released July 2023 and with the follow-on release of 3.7.1 a few
months later, introduced a large expansion of the Gremlin language, providing
long-awaited features for manipulating strings, collections, and dates. There were
other major features as well, such as TinkerGraph gaining some simple transactional
features and the ability for properties to be returned on elements from Gremlin 
Server, rather than only getting references. Notable improvements include:

* New Gremlin steps for working with strings: 'asString', 'concat', 'length', 
'toLower', 'toUpper', 'trim', 'lTrim', 'rTrim', 'reverse', 'replace', 'split', 
'substring, and 'format'.
* New Gremlin steps for working with collections: 'any', 'all', 'product', 'merge', 
'intersect', 'combine', 'conjoin', 'difference', 'disjunct,' and 'reverse'.
* A new Gremlin steps for working with dates: 'asDate', 'dateAdd' and 
'dateDiff'.
* The 'union' step became available as a start step.
* Improved syntax for specifying cardinality directly within a 'Map' for use with 
'mergeV'.
* TinkerGraph gained support for simple transactions.
* Graph elements like 'Vertex' and 'Edge' can now be returned from Gremlin Server 
with their properties attached using the 'materializeProperties' option.

NOTE: Full details of all the new features added in the TinkerPop 3.7.x releases can 
be found at the following link:
https://github.com/apache/tinkerpop/blob/3.7-dev/CHANGELOG.asciidoc

[[tp38intro]]
==== TinkerPop 3.8

TinkerPop 3.8.0 was released November 2025 and established a wide mix of features
and improvements to Gremlin semantics designed to enhance language consistency. Some 
of these changes do lead to behaviors that break from previous versions of TinkerPop, 
but are expected to stay consistent with TinkerPop 4.0, which should help ease the 
migration there when 4.0 eventually releases. Here are some of the important 
highlights to consider from this release:

* New Gremlin steps for type conversions: 'asBool' and 'asNumber'.
* Added the new 'typeOf' predicate to make it possible to filter traverser objects
given their data type.
* The 'none' step was renamed to 'discard', and 'none' has been modified to take 'P'
as an argument, whose behavior is now a complement to 'any' and 'all' steps.
* The minimum Java version supported is JDK11.
* The default implementation for the 'date' data type for Java is 'OffsetDateTime'
rather than 'java.util.Date', which means that steps like 'asDate' and helpers like
the 'datetime' function will return 'OffsetDateTime' whose string representation is
an ISO 8601 format.
* Creation of 'g' has been simplified slightly by replacing more verbose 
construction options of 'traversal().withEmbedded(...)' and 
'traversal().withRemote(...)' with a single 'traversal().with(...)'.
* The 'split' method splits a string to characters if given an empty string as a 
separator argument.
* The Gremlin language removed syntax for 'Vertex', made use of 'new' optional, 
included support for 'withoutStrategies,' and removed 'Map' key restrictions related
to reserved words.
* The semantics for the 'choose' step changed to match the first option only, pass
through traversers when the choice is unproductive or the determined choice 
unmatched, and introduces a new 'Pick.unproductive' option.
* Gremlin no longer follows Groovy by defaulting float values to 'BigDecimal' – they
go to 'double' instead.
* The 'valueMap', 'propertyMap', 'groupCount', 'dedup', 'sack', 'sample', 'aggregate'
steps can no longer take 'by' modulators beyond the number each step expects.
* Included the air-routes dataset, as is used in this book, as official sample data
in the distribution.
* The form of 'has' that takes a key and a 'Traversal' as an argument has been
removed to prevent confusion around its functionality and to prepare for a revised
implementation of it in 4.0.0.
* The semantics for 'limit', 'skip,' and 'range' with 'global' scope are tracked per
iteration inside 'repeat'.
* The semantics for 'limit', 'skip,' and 'range', with 'local' scope will no longer
automatically unwrap a single item in a list if there is only one object present.

NOTE: Full details of all the new features added in the TinkerPop 3.8.x releases can 
be found at the following link:
https://github.com/apache/tinkerpop/blob/3.8-dev/CHANGELOG.asciidoc

[[tp40intro]]
==== TinkerPop 4.0

TinkerPop 4.0.0 has released a beta version for early evaluation of specific features
and remains under active development. We mention it here for awareness but do not
intend to cover any features it offers until its full official release. We will only
note that the intention of the TinkerPop Community is for 4.0.0 to have the same
semantics for Gremlin as 3.8.0. As a result, all the Gremlin examples provided in 
this second edition of Practical Gremlin will work equally well for both versions.

[[whygraph]]
=== So what is a graph database and why should I care?

This book is mainly intended to be a tutorial in working with graph databases and
related technology using the Gremlin query language. However, it is worth spending
just a few moments to summarize why it is important to understand what a graph
database is, what some good use cases for graphs are and why you should care in a
world that is already full of all kinds of SQL and NoSQL databases. In this book we
are going to be discussing 'directed property graphs'. At the conceptual level, these
types of graphs are quite simple to understand. You have three basic building blocks:
vertices, edges, and properties. Vertices represent "things" such as people or
places. Edges represent connections between those vertices, and properties are
information added to the vertices and edges as needed. The 'directed' part of the
name means that any edge has a direction. It goes 'out' from one vertex and 'in' to
another. You will sometimes hear people use the word 'digraph' as shorthand for
'directed graph'. Consider the relationship "Kelvin knows Jack". This could be
modeled as a vertex for each of the people and an edge for the relationship as
follows.

[.text-center]
Kelvin -- knows -> Jack

Note the arrow which implies the direction of the relationship. If we wanted to
record the fact that Jack also admits to knowing Kelvin, we would need to add a
second edge from Jack to Kelvin. Properties could be added to each person to give
more information about them. For example, my age might be a property on my vertex.

It turns out that Jack really likes cats. We might want to store that in our graph as
well so we could create the relationship:

[.text-center]
Jack -- likes -> Cats

Now that we have a bit more in our graph, we could answer the following question:
"who does Kelvin know that likes cats?"

[.text-center]
Kelvin -- knows -> Jack -- likes -> Cats

This is a simple example, but hopefully you can already see that we are modeling our
data the way we think about it in the real world. Armed with this knowledge, you now
have all the basic building blocks you need to start thinking about how you might
model things you are familiar with as a graph.

So getting back to the question of "why should I care?", well, if something looks
like a graph, then wouldn't it be great if we could model it that way. Many things in
our everyday lives center around things that can very nicely be represented in a
graph. Things such as your social and business networks, the route you take to get to
work, the phone network, airline route choices for trips you need to take are all
great candidates. There are also many great business applications for graph databases
and algorithms. These include recommendation systems, crime prevention, and fraud
detection to name but three.

The reverse is also true. If something does not feel like a graph, then don't try to
force it to be. Your videos are probably doing quite nicely living in the object
store where you currently have them. A sales ledger system built using a relational
database is probably doing just fine where it is, and likewise a document store is
quite possibly just the right place to be storing your documents. So "using the right
tool for the job" remains as valid a phrase here as elsewhere. Where graph databases
come into their own is when the data you are storing is intrinsically linked by its
very nature, the air-routes network used as the basis for all the examples in this
book being a perfect example of such a situation.

Those of you that looked at graphs as part of a computer science course are correct
if your reaction was "Surely graphs have been around for ages, why is this considered
new?". Indeed, Leonard Euler is credited with demonstrating the first graph problem
and inventing the whole concept of "Graph Theory" all the way back in 1763 when he
investigated the now famous "Seven Bridges of Koenigsberg" problem.

If you want to read a bit more about graph theory and its present-day application,
you can find a lot of good information online. Here's a Wikipedia link to get you
started: https://en.wikipedia.org/wiki/Graph_theory

So, given Graph Theory is anything but a new idea, why is it that only recently we
are seeing a massive growth in the building and deployment of graph database systems
and applications? At least part of the answer is that computer hardware and software
have reached the point where you can build large big data systems that scale well for
a reasonable price. In fact, it's even easier than ever to build large systems
because you don't have to buy the hardware that your system will run on when you use
the cloud.

While you can certainly run a graph database on your laptop--I do just that every
day--the reality is that in production, at scale, they are big data systems. Large
graphs commonly have many billions of vertices and edges in them, taking up petabytes
of data on disk. Graph algorithms can be both compute- and memory-intensive, and it
is only fairly recent that deploying the necessary resources for such big data
systems has made financial sense for more everyday uses in business, and not just in
government or academia. Graph databases are becoming much more broadly adopted across
the spectrum, from high-end scientific research to financial networks and beyond.

Another factor that has really helped start this graph database revolution is the
availability of high-quality open source technology. There are a lot of great open
source projects addressing everything from the databases you need to store the graph
data, to the query languages used to traverse them, all the way up to visually
displaying graphs as part of the user interface layer. In particular, it is so-called
'property graphs' where we are seeing the broadest development and uptake. In a
property graph, both vertices and edges can have properties (effectively, key-value
pairs) associated with them. There are many styles of graph that you may end up
building, and there have been whole books written on these various design patterns,
but the property graph technology we will focus on in this book can support all the
most common usage patterns. If you hear phrases such as 'directed graph' and
'undirected graph', or 'cyclic' and 'acyclic' graph, and many more as you work with
graph databases, a quick online search will get you to a place where you can get
familiar with that terminology. A deep discussion of these patterns is beyond the
scope of this book, and it's in no way essential to have a full background in
graph theory to get productive quickly.

A third, and equally important, factor in the growth we are seeing in graph database
adoption is the low barrier of entry for programmers. As you will see from the
examples in this book, someone wanting to experiment with graph technology can
download the Apache TinkerPop package and as long as Java 11+ is installed, be up and
running with zero configuration (other than unzipping of the files), in as little as
five minutes. Graph databases do not force you to define schemas or specify the
layout of tables and columns before you can get going and start building a graph.
Programmers also seem to find the graph style of programming quite intuitive as it
closely models the way they think of the world.

Graph database technology should not be viewed as a "rip and replace" technology, but
as very much complementary to other databases that you may already have deployed. One
common use case is for the graph to be used as a form of smart index into other data
stores. This is sometimes called having a polyglot data architecture.

[[nodevert]]
=== A word about terminology

The words 'node' and 'vertex' are synonymous when discussing a graph. This book will
prefer the term 'vertex' and 'vertices' as the Apache TinkerPop documentation almost
exclusively uses it when discussing Gremlin queries and other concepts. We will only
see a shade of the term 'node' when we refer to "supernodes", relating to vertices
of an especially high degree, as this term has wide acceptance independently of
TinkerPop. By the same token, this book will be consistent with the official
TinkerPop documentation when discussing the connections between vertices, where we
will use the term 'edge' or the plural form, 'edges'. In other books and articles you
may also see terms like 'relationship' or 'arc' used.  Again, these terms are
synonymous in the context of graphs.