// vim: set tw=85 cc=+1 wrap spell redrawtime=20000:

[[fr]]
== FURTHER READING

Below you will find a selection of links to additional material related to the topics
covered in this book. The links include additional web sites maintained by the Apache
TinkerPop community as well as some mailing lists where Gremlin and related topics
are discussed daily.

[[tplinks]]
Additional Apache TinkerPop community links
.Official Apache TinkerPop home page and Gremlin downloads
https://tinkerpop.apache.org/

.Current Apache TinkerPop Reference Documentation
https://tinkerpop.apache.org/docs/current/reference/

.Apache TinkerPop JavaDoc API reference material
https://tinkerpop.apache.org/javadocs/current/core/

https://tinkerpop.apache.org/javadocs/current/full/

.Gremlin serialization and file formats documentation
https://tinkerpop.apache.org/docs/current/dev/io/

.Useful Gremlin "recipes"
https://tinkerpop.apache.org/docs/current/recipes/

.Apache TinkerPop documentation describing new features per release
https://tinkerpop.apache.org/docs/current/upgrade/

.Apache TinkerPop documentation for graph database providers
https://tinkerpop.apache.org/docs/current/dev/provider/

.Apache TinkerPop documentation for making contributions
https://tinkerpop.apache.org/docs/current/dev/developer/

[[tutorials]]
Tutorials
There are a series of tutorials that can be found at the link below.

.Apache TinkerPop Tutorials
https://tinkerpop.apache.org/docs/current/tutorials/

The tutorials include the following

Getting Started::
* https://tinkerpop.apache.org/docs/current/tutorials/getting-started/
Gremlin's Anatomy::
* https://tinkerpop.apache.org/docs/current/tutorials/gremlins-anatomy/
The Gremlin Console::
* https://tinkerpop.apache.org/docs/current/tutorials/the-gremlin-console/

[[gremlindiscussionlists]]
=== Gremlin related mailing lists and discussion groups

.Apache Tinkerpop Discord Server
https://discord.gg/tinkerpop

.Public mailing list for Gremlin users
https://groups.google.com/forum/#!forum/gremlin-users

.Apache TinkerPop developers mailing list archive
https://lists.apache.org/list.html?dev@tinkerpop.apache.org

.Stack Overflow posts tagged with "gremlin"
https://stackoverflow.com/questions/tagged/gremlin

