// vim: set tw=85 cc=+1 wrap spell redrawtime=20000:

[[fr]]
== FURTHER READING

Below you will find a selection of links to additional material related to the topics
covered in this book. The links include additional web sites maintained by the Apache
TinkerPop community as well as some mailing lists where Gremlin and related topics
are discussed daily.

[[tplinks]]
Additional Apache TinkerPop community links
.Official Apache TinkerPop home page and Gremlin downloads
http://tinkerpop.apache.org/

.Current Apache TinkerPop Reference Documentation
http://tinkerpop.apache.org/docs/current/reference/

.Apache TinkerPop JavaDoc API reference material
http://tinkerpop.apache.org/javadocs/current/core/

http://tinkerpop.apache.org/javadocs/current/full/

.Gremlin serialization and file formats documentation
http://tinkerpop.apache.org/docs/current/dev/io/

.Useful Gremlin "recipes"
http://tinkerpop.apache.org/docs/current/recipes/

.Apache TinkerPop documentation describing new features per release
http://tinkerpop.apache.org/docs/current/upgrade/

.Apache TinkerPop documentation for graph database providers
http://tinkerpop.apache.org/docs/current/dev/provider/

.Apache TinkerPop documentation for making contributions
https://tinkerpop.apache.org/docs/current/dev/developer/

[[tutorials]]
Tutorials
There are a series of tutorials that can be found at the link below.

.Apache TinkerPop Tutorials
http://tinkerpop.apache.org/docs/current/tutorials/

The tutorials include the following

Getting Started::
* http://tinkerpop.apache.org/docs/current/tutorials/getting-started/
Gremlin's Anatomy::
* http://tinkerpop.apache.org/docs/current/tutorials/gremlins-anatomy/
The Gremlin Console::
* http://tinkerpop.apache.org/docs/current/tutorials/the-gremlin-console/

[[gremlindiscussionlists]]
=== Gremlin related mailing lists and discussion groups

.Apache Tinkerpop Discord Server
https://discord.gg/tinkerpop

.Public mailing list for Gremlin users
https://groups.google.com/forum/#!forum/gremlin-users

.Apache TinkerPop developers mailing list archive
https://lists.apache.org/list.html?dev@tinkerpop.apache.org

.Stack Overflow posts tagged with "gremlin"
https://stackoverflow.com/questions/tagged/gremlin

